-- Existing CUID session identifiers cannot be converted safely. Sessions are
-- disposable, so recreate only this identifier column and invalidate sessions.
ALTER TABLE "Session" DROP CONSTRAINT "Session_pkey";
ALTER TABLE "Session" DROP COLUMN "id";
ALTER TABLE "Session" ADD COLUMN "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE "Session" ADD CONSTRAINT "Session_pkey" PRIMARY KEY ("id");